// Lista completa de países ordenados alfabeticamente
export const COUNTRIES = [
  { code: "AF", name: "Afeganistão" },
  { code: "ZA", name: "África do Sul" },
  { code: "AL", name: "Albânia" },
  { code: "DE", name: "Alemanha" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AG", name: "Antígua e Barbuda" },
  { code: "SA", name: "Arábia Saudita" },
  { code: "DZ", name: "Argélia" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armênia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Austrália" },
  { code: "AT", name: "Áustria" },
  { code: "AZ", name: "Azerbaijão" },
  { code: "BS", name: "Bahamas" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BH", name: "Bahrein" },
  { code: "BE", name: "Bélgica" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermudas" },
  { code: "BY", name: "Bielorrússia" },
  { code: "BO", name: "Bolívia" },
  { code: "BA", name: "Bósnia e Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brasil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgária" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "BT", name: "Butão" },
  { code: "CV", name: "Cabo Verde" },
  { code: "CM", name: "Camarões" },
  { code: "KH", name: "Camboja" },
  { code: "CA", name: "Canadá" },
  { code: "QA", name: "Catar" },
  { code: "KZ", name: "Cazaquistão" },
  { code: "TD", name: "Chade" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CY", name: "Chipre" },
  { code: "SG", name: "Cingapura" },
  { code: "CO", name: "Colômbia" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo" },
  { code: "KP", name: "Coreia do Norte" },
  { code: "KR", name: "Coreia do Sul" },
  { code: "CI", name: "Costa do Marfim" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croácia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "DK", name: "Dinamarca" },
  { code: "DJ", name: "Djibuti" },
  { code: "DM", name: "Dominica" },
  { code: "EG", name: "Egito" },
  { code: "SV", name: "El Salvador" },
  { code: "AE", name: "Emirados Árabes Unidos" },
  { code: "EC", name: "Equador" },
  { code: "ER", name: "Eritreia" },
  { code: "SK", name: "Eslováquia" },
  { code: "SI", name: "Eslovênia" },
  { code: "ES", name: "Espanha" },
  { code: "US", name: "Estados Unidos" },
  { code: "EE", name: "Estônia" },
  { code: "ET", name: "Etiópia" },
  { code: "FJ", name: "Fiji" },
  { code: "PH", name: "Filipinas" },
  { code: "FI", name: "Finlândia" },
  { code: "FR", name: "França" },
  { code: "GA", name: "Gabão" },
  { code: "GM", name: "Gâmbia" },
  { code: "GH", name: "Gana" },
  { code: "GE", name: "Geórgia" },
  { code: "GI", name: "Gibraltar" },
  { code: "GD", name: "Granada" },
  { code: "GR", name: "Grécia" },
  { code: "GL", name: "Groenlândia" },
  { code: "GP", name: "Guadalupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GY", name: "Guiana" },
  { code: "GF", name: "Guiana Francesa" },
  { code: "GW", name: "Guiné-Bissau" },
  { code: "GN", name: "Guiné" },
  { code: "GQ", name: "Guiné Equatorial" },
  { code: "HT", name: "Haiti" },
  { code: "NL", name: "Holanda" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungria" },
  { code: "YE", name: "Iêmen" },
  { code: "IN", name: "Índia" },
  { code: "ID", name: "Indonésia" },
  { code: "IQ", name: "Iraque" },
  { code: "IR", name: "Irã" },
  { code: "IE", name: "Irlanda" },
  { code: "IS", name: "Islândia" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Itália" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japão" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordânia" },
  { code: "KW", name: "Kuwait" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesoto" },
  { code: "LV", name: "Letônia" },
  { code: "LB", name: "Líbano" },
  { code: "LR", name: "Libéria" },
  { code: "LY", name: "Líbia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituânia" },
  { code: "LU", name: "Luxemburgo" },
  { code: "MO", name: "Macau" },
  { code: "MK", name: "Macedônia do Norte" },
  { code: "MG", name: "Madagascar" },
  { code: "MY", name: "Malásia" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Maldivas" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MA", name: "Marrocos" },
  { code: "MQ", name: "Martinica" },
  { code: "MU", name: "Maurício" },
  { code: "MR", name: "Mauritânia" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "México" },
  { code: "MM", name: "Myanmar" },
  { code: "FM", name: "Micronésia" },
  { code: "MZ", name: "Moçambique" },
  { code: "MD", name: "Moldávia" },
  { code: "MC", name: "Mônaco" },
  { code: "MN", name: "Mongólia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "NA", name: "Namíbia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NI", name: "Nicarágua" },
  { code: "NE", name: "Níger" },
  { code: "NG", name: "Nigéria" },
  { code: "NO", name: "Noruega" },
  { code: "NC", name: "Nova Caledônia" },
  { code: "NZ", name: "Nova Zelândia" },
  { code: "OM", name: "Omã" },
  { code: "PW", name: "Palau" },
  { code: "PA", name: "Panamá" },
  { code: "PG", name: "Papua-Nova Guiné" },
  { code: "PK", name: "Paquistão" },
  { code: "PY", name: "Paraguai" },
  { code: "PE", name: "Peru" },
  { code: "PF", name: "Polinésia Francesa" },
  { code: "PL", name: "Polônia" },
  { code: "PR", name: "Porto Rico" },
  { code: "PT", name: "Portugal" },
  { code: "KE", name: "Quênia" },
  { code: "KG", name: "Quirguistão" },
  { code: "GB", name: "Reino Unido" },
  { code: "CF", name: "República Centro-Africana" },
  { code: "CD", name: "República Democrática do Congo" },
  { code: "DO", name: "República Dominicana" },
  { code: "CZ", name: "República Tcheca" },
  { code: "RE", name: "Reunião" },
  { code: "RO", name: "Romênia" },
  { code: "RW", name: "Ruanda" },
  { code: "RU", name: "Rússia" },
  { code: "EH", name: "Saara Ocidental" },
  { code: "PM", name: "Saint Pierre e Miquelon" },
  { code: "WS", name: "Samoa" },
  { code: "AS", name: "Samoa Americana" },
  { code: "SM", name: "San Marino" },
  { code: "SH", name: "Santa Helena" },
  { code: "LC", name: "Santa Lúcia" },
  { code: "KN", name: "São Cristóvão e Nevis" },
  { code: "ST", name: "São Tomé e Príncipe" },
  { code: "VC", name: "São Vicente e Granadinas" },
  { code: "SC", name: "Seychelles" },
  { code: "SN", name: "Senegal" },
  { code: "SL", name: "Serra Leoa" },
  { code: "RS", name: "Sérvia" },
  { code: "SY", name: "Síria" },
  { code: "SO", name: "Somália" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SZ", name: "Suazilândia" },
  { code: "SD", name: "Sudão" },
  { code: "SS", name: "Sudão do Sul" },
  { code: "SE", name: "Suécia" },
  { code: "CH", name: "Suíça" },
  { code: "SR", name: "Suriname" },
  { code: "TJ", name: "Tadjiquistão" },
  { code: "TH", name: "Tailândia" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzânia" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad e Tobago" },
  { code: "TN", name: "Tunísia" },
  { code: "TC", name: "Turks e Caicos" },
  { code: "TM", name: "Turcomenistão" },
  { code: "TR", name: "Turquia" },
  { code: "TV", name: "Tuvalu" },
  { code: "UA", name: "Ucrânia" },
  { code: "UG", name: "Uganda" },
  { code: "UY", name: "Uruguai" },
  { code: "UZ", name: "Uzbequistão" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vaticano" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnã" },
  { code: "VG", name: "Ilhas Virgens Britânicas" },
  { code: "VI", name: "Ilhas Virgens Americanas" },
  { code: "ZM", name: "Zâmbia" },
  { code: "ZW", name: "Zimbábue" },
];

// Estados dos EUA
export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

// Estados do Brasil
export const BR_STATES = [
  { code: "AC", name: "Acre" },
  { code: "AL", name: "Alagoas" },
  { code: "AP", name: "Amapá" },
  { code: "AM", name: "Amazonas" },
  { code: "BA", name: "Bahia" },
  { code: "CE", name: "Ceará" },
  { code: "DF", name: "Distrito Federal" },
  { code: "ES", name: "Espírito Santo" },
  { code: "GO", name: "Goiás" },
  { code: "MA", name: "Maranhão" },
  { code: "MT", name: "Mato Grosso" },
  { code: "MS", name: "Mato Grosso do Sul" },
  { code: "MG", name: "Minas Gerais" },
  { code: "PA", name: "Pará" },
  { code: "PB", name: "Paraíba" },
  { code: "PR", name: "Paraná" },
  { code: "PE", name: "Pernambuco" },
  { code: "PI", name: "Piauí" },
  { code: "RJ", name: "Rio de Janeiro" },
  { code: "RN", name: "Rio Grande do Norte" },
  { code: "RS", name: "Rio Grande do Sul" },
  { code: "RO", name: "Rondônia" },
  { code: "RR", name: "Roraima" },
  { code: "SC", name: "Santa Catarina" },
  { code: "SP", name: "São Paulo" },
  { code: "SE", name: "Sergipe" },
  { code: "TO", name: "Tocantins" },
];

// Províncias do Canadá
export const CA_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];

// Distritos de Portugal (18 distritos + 2 regiões autônomas)
export const PT_DISTRICTS = [
  { code: "01", name: "Aveiro" },
  { code: "02", name: "Beja" },
  { code: "03", name: "Braga" },
  { code: "04", name: "Bragança" },
  { code: "05", name: "Castelo Branco" },
  { code: "06", name: "Coimbra" },
  { code: "07", name: "Évora" },
  { code: "08", name: "Faro" },
  { code: "09", name: "Guarda" },
  { code: "10", name: "Leiria" },
  { code: "11", name: "Lisboa" },
  { code: "12", name: "Portalegre" },
  { code: "13", name: "Porto" },
  { code: "14", name: "Santarém" },
  { code: "15", name: "Setúbal" },
  { code: "16", name: "Viana do Castelo" },
  { code: "17", name: "Vila Real" },
  { code: "18", name: "Viseu" },
  { code: "20", name: "Açores" },
  { code: "30", name: "Madeira" },
];

// Comunidades Autônomas da Espanha
export const ES_COMMUNITIES = [
  { code: "AN", name: "Andaluzia" },
  { code: "AR", name: "Aragão" },
  { code: "AS", name: "Astúrias" },
  { code: "IB", name: "Ilhas Baleares" },
  { code: "CN", name: "Ilhas Canárias" },
  { code: "CB", name: "Cantábria" },
  { code: "CL", name: "Castela e Leão" },
  { code: "CM", name: "Castela-La Mancha" },
  { code: "CT", name: "Catalunha" },
  { code: "EX", name: "Extremadura" },
  { code: "GA", name: "Galiza" },
  { code: "MD", name: "Madrid" },
  { code: "MC", name: "Múrcia" },
  { code: "NC", name: "Navarra" },
  { code: "PV", name: "País Basco" },
  { code: "RI", name: "La Rioja" },
  { code: "VC", name: "Comunidade Valenciana" },
];

// Regiões da França
export const FR_REGIONS = [
  { code: "ARA", name: "Auvergne-Rhône-Alpes" },
  { code: "BFC", name: "Bourgogne-Franche-Comté" },
  { code: "BRE", name: "Bretanha" },
  { code: "CVL", name: "Centre-Val de Loire" },
  { code: "COR", name: "Córsega" },
  { code: "GES", name: "Grand Est" },
  { code: "HDF", name: "Hauts-de-France" },
  { code: "IDF", name: "Île-de-France" },
  { code: "NOR", name: "Normandia" },
  { code: "NAQ", name: "Nouvelle-Aquitaine" },
  { code: "OCC", name: "Occitânia" },
  { code: "PDL", name: "Pays de la Loire" },
  { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
];

// Estados da Alemanha (Länder)
export const DE_STATES = [
  { code: "BW", name: "Baden-Württemberg" },
  { code: "BY", name: "Baviera" },
  { code: "BE", name: "Berlim" },
  { code: "BB", name: "Brandemburgo" },
  { code: "HB", name: "Bremen" },
  { code: "HH", name: "Hamburgo" },
  { code: "HE", name: "Hesse" },
  { code: "MV", name: "Mecklemburgo-Pomerânia Ocidental" },
  { code: "NI", name: "Baixa Saxônia" },
  { code: "NW", name: "Renânia do Norte-Vestfália" },
  { code: "RP", name: "Renânia-Palatinado" },
  { code: "SL", name: "Sarre" },
  { code: "SN", name: "Saxônia" },
  { code: "ST", name: "Saxônia-Anhalt" },
  { code: "SH", name: "Schleswig-Holstein" },
  { code: "TH", name: "Turíngia" },
];

// Regiões da Itália
export const IT_REGIONS = [
  { code: "ABR", name: "Abruzzo" },
  { code: "BAS", name: "Basilicata" },
  { code: "CAL", name: "Calábria" },
  { code: "CAM", name: "Campânia" },
  { code: "EMR", name: "Emília-Romanha" },
  { code: "FVG", name: "Friuli-Venezia Giulia" },
  { code: "LAZ", name: "Lácio" },
  { code: "LIG", name: "Ligúria" },
  { code: "LOM", name: "Lombardia" },
  { code: "MAR", name: "Marche" },
  { code: "MOL", name: "Molise" },
  { code: "PIE", name: "Piemonte" },
  { code: "PUG", name: "Apúlia" },
  { code: "SAR", name: "Sardenha" },
  { code: "SIC", name: "Sicília" },
  { code: "TOS", name: "Toscana" },
  { code: "TAA", name: "Trentino-Alto Ádige" },
  { code: "UMB", name: "Úmbria" },
  { code: "VDA", name: "Vale de Aosta" },
  { code: "VEN", name: "Vêneto" },
];

// Províncias da Argentina
export const AR_PROVINCES = [
  { code: "BA", name: "Buenos Aires" },
  { code: "CT", name: "Catamarca" },
  { code: "CC", name: "Chaco" },
  { code: "CH", name: "Chubut" },
  { code: "CB", name: "Córdoba" },
  { code: "CR", name: "Corrientes" },
  { code: "ER", name: "Entre Ríos" },
  { code: "FO", name: "Formosa" },
  { code: "JY", name: "Jujuy" },
  { code: "LP", name: "La Pampa" },
  { code: "LR", name: "La Rioja" },
  { code: "MZ", name: "Mendoza" },
  { code: "MN", name: "Misiones" },
  { code: "NQ", name: "Neuquén" },
  { code: "RN", name: "Río Negro" },
  { code: "SA", name: "Salta" },
  { code: "SJ", name: "San Juan" },
  { code: "SL", name: "San Luis" },
  { code: "SC", name: "Santa Cruz" },
  { code: "SF", name: "Santa Fe" },
  { code: "SE", name: "Santiago del Estero" },
  { code: "TF", name: "Tierra del Fuego" },
  { code: "TM", name: "Tucumán" },
  { code: "CF", name: "Ciudad Autónoma de Buenos Aires" },
];

// Estados do México
export const MX_STATES = [
  { code: "AGU", name: "Aguascalientes" },
  { code: "BCN", name: "Baja California" },
  { code: "BCS", name: "Baja California Sur" },
  { code: "CAM", name: "Campeche" },
  { code: "CHP", name: "Chiapas" },
  { code: "CHH", name: "Chihuahua" },
  { code: "COA", name: "Coahuila" },
  { code: "COL", name: "Colima" },
  { code: "DIF", name: "Cidade do México" },
  { code: "DUR", name: "Durango" },
  { code: "GUA", name: "Guanajuato" },
  { code: "GRO", name: "Guerrero" },
  { code: "HID", name: "Hidalgo" },
  { code: "JAL", name: "Jalisco" },
  { code: "MEX", name: "Estado do México" },
  { code: "MIC", name: "Michoacán" },
  { code: "MOR", name: "Morelos" },
  { code: "NAY", name: "Nayarit" },
  { code: "NLE", name: "Nuevo León" },
  { code: "OAX", name: "Oaxaca" },
  { code: "PUE", name: "Puebla" },
  { code: "QUE", name: "Querétaro" },
  { code: "ROO", name: "Quintana Roo" },
  { code: "SLP", name: "San Luis Potosí" },
  { code: "SIN", name: "Sinaloa" },
  { code: "SON", name: "Sonora" },
  { code: "TAB", name: "Tabasco" },
  { code: "TAM", name: "Tamaulipas" },
  { code: "TLA", name: "Tlaxcala" },
  { code: "VER", name: "Veracruz" },
  { code: "YUC", name: "Yucatán" },
  { code: "ZAC", name: "Zacatecas" },
];

// Tipos de envelope padrão (quando object = "doc")
export const ENVELOPE_TYPES = [
  { value: "envelope_a4", label: "Envelope A4", dimensions: "22 x 31 cm" },
  { value: "envelope_c4", label: "Envelope C4", dimensions: "23 x 32 cm" },
  { value: "envelope_c5", label: "Envelope C5", dimensions: "16 x 23 cm" },
  { value: "envelope_dl", label: "Envelope DL", dimensions: "11 x 22 cm" },
  { value: "envelope_legal", label: "Envelope Legal", dimensions: "24 x 37 cm" },
  { value: "envelope_letter", label: "Envelope Letter", dimensions: "22 x 28 cm" },
  { value: "padded_envelope", label: "Envelope Acolchoado", dimensions: "24 x 36 cm" },
];

// Interface para definir divisões administrativas por país
interface CountryDivisions {
  label: string; // Nome do tipo de divisão (Estado, Distrito, Província, etc.)
  divisions: Array<{ code: string; name: string }>;
}

// Mapeamento de divisões por país
const DIVISIONS_BY_COUNTRY: Record<string, CountryDivisions> = {
  PT: { label: "Distrito", divisions: PT_DISTRICTS },
  ES: { label: "Comunidade Autônoma", divisions: ES_COMMUNITIES },
  FR: { label: "Região", divisions: FR_REGIONS },
  DE: { label: "Estado", divisions: DE_STATES },
  IT: { label: "Região", divisions: IT_REGIONS },
  AR: { label: "Província", divisions: AR_PROVINCES },
  MX: { label: "Estado", divisions: MX_STATES },
  US: { label: "Estado", divisions: US_STATES },
  BR: { label: "Estado", divisions: BR_STATES },
  CA: { label: "Província", divisions: CA_PROVINCES },
};

// Função helper para obter divisões por país
export function getDivisionsByCountry(countryCode: string): CountryDivisions | null {
  return DIVISIONS_BY_COUNTRY[countryCode] || null;
}

// Função legada para compatibilidade (deprecated)
export function getStatesByCountry(countryCode: string) {
  const result = getDivisionsByCountry(countryCode);
  return result ? result.divisions : [];
}
